# Generated by Django 2.2.4 on 2019-08-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='holiday',
            old_name='begining_date',
            new_name='vacation_begining',
        ),
        migrations.AddField(
            model_name='holiday',
            name='vacation_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holiday',
            name='vacation_status',
            field=models.IntegerField(default=0),
        ),
    ]
