# Generated by Django 2.2.4 on 2019-08-23 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_auto_20190823_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='vacation_reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='holiday.VacationReason'),
        ),
    ]
